import type { MemoryItem, MediaRef } from "@memorium/core";
import { contentHash, generateId, nowIso } from "@memorium/core";

type DemoSample = Omit<MemoryItem, "id" | "memorialId" | "importedAt" | "contentHash" | "mediaRefs"> & {
  mediaRefs?: Omit<MediaRef, "id">[];
};

function demoImage(filename: string): Omit<MediaRef, "id"> {
  return {
    vaultPath: `demo/media/${filename}`,
    mimeType: "image/svg+xml",
    originalFilename: filename,
    width: 1080,
    height: 1080,
  };
}

/** Sample memories for POC demos — fictional content inspired by real archive shapes */
export function createDemoItems(memorialId: string): MemoryItem[] {
  const importedAt = nowIso();

  const samples: DemoSample[] = [
    {
      type: "post",
      source: "meta_facebook",
      title: "Sunday dinner tradition",
      text: "Nothing beats Rose's arroz con pollo. Every Sunday the whole block could smell it cooking. She always made enough for whoever showed up — and someone always showed up.",
      occurredAt: "2018-03-11T18:30:00.000Z",
      personIds: [],
      metadata: { reactions: 47, comments: 12 },
    },
    {
      type: "post",
      source: "meta_instagram",
      title: "Garden in bloom",
      text: "Her roses are finally opening 🌹 Third year in a row she's won the neighborhood garden club ribbon. #roses #garden #spring",
      occurredAt: "2019-05-04T14:22:00.000Z",
      personIds: [],
      mediaRefs: [demoImage("instagram-garden.svg")],
      metadata: { likes: 89, lat: 41.8781, lng: -87.6298, place: "Rose's garden, Chicago", tags: ["garden", "roses", "spring"] },
    },
    {
      type: "message",
      source: "meta_messenger",
      title: "Message from Maria",
      text: "Tía Rose — can you send me the recipe for the flan? The one you made for abuela's birthday. I want to make it for Sofia's quinceañera.",
      occurredAt: "2020-02-14T21:05:00.000Z",
      personIds: [],
      metadata: { sender: "Maria" },
    },
    {
      type: "message",
      source: "meta_messenger",
      title: "Message from Rose",
      text: "Of course mija! I'll write it out by hand and mail it to you. Some things shouldn't live only on a phone. Love you 💕",
      occurredAt: "2020-02-14T21:18:00.000Z",
      personIds: [],
      metadata: { sender: "Rose Martinez" },
    },
    {
      type: "email",
      source: "email",
      title: "Re: College move-in day",
      text: "Dear James,\n\nI packed the quilt your grandfather made — the blue one. Take care of it. Call me when you get there, even if it's late. I'll be awake.\n\nLove always,\nMom",
      occurredAt: "2017-08-22T09:15:00.000Z",
      personIds: [],
      metadata: { from: "rose.martinez@gmail.com", to: "james.martinez@university.edu" },
    },
    {
      type: "email",
      source: "email",
      title: "Photos from the reunion",
      text: "Hi everyone,\n\nAttached are the photos from last weekend. What a wonderful time seeing all of you. Let's not wait another five years!\n\nRose",
      occurredAt: "2015-07-03T16:40:00.000Z",
      personIds: [],
      metadata: { from: "rose.martinez@gmail.com", to: "family@martinez-clan.com" },
    },
    {
      type: "message",
      source: "whatsapp",
      title: "WhatsApp from James",
      text: "Mom, landed safe. Room is small but the quilt is on the bed already. Miss you.",
      occurredAt: "2017-08-22T22:30:00.000Z",
      personIds: [],
      metadata: { sender: "James", chat: "Family Group" },
    },
    {
      type: "message",
      source: "whatsapp",
      title: "WhatsApp from Rose",
      text: "So proud of you. Eat something besides ramen. I left money in the envelope — don't argue with me.",
      occurredAt: "2017-08-22T22:45:00.000Z",
      personIds: [],
      metadata: { sender: "Rose Martinez", chat: "Family Group" },
    },
    {
      type: "message",
      source: "imessage",
      title: "iMessage from James",
      text: "Mom are you awake? Flight got cancelled. Stuck at O'Hare.",
      occurredAt: "2019-11-27T03:14:00.000Z",
      personIds: [],
      metadata: { sender: "James", service: "iMessage" },
    },
    {
      type: "message",
      source: "imessage",
      title: "iMessage from Rose",
      text: "Always awake for you mijo. There's a quilt in the hall closet if they give you blankets. Come home whenever — turkey keeps.",
      occurredAt: "2019-11-27T03:22:00.000Z",
      personIds: [],
      metadata: { sender: "Rose Martinez", service: "iMessage" },
    },
    {
      type: "message",
      source: "google_messages",
      title: "Text from Maria",
      text: "Tía the roses in your last post look incredible!! 😍 Can I come by Saturday for a cutting?",
      occurredAt: "2019-05-06T19:45:00.000Z",
      personIds: [],
      metadata: { sender: "Maria", service: "Google Messages" },
    },
    {
      type: "message",
      source: "google_messages",
      title: "Text from Rose",
      text: "Of course! I'll put coffee on. Bring Sofia — I have cookies from yesterday.",
      occurredAt: "2019-05-06T19:52:00.000Z",
      personIds: [],
      metadata: { sender: "Rose Martinez", service: "Google Messages" },
    },
    {
      type: "post",
      source: "meta_facebook",
      title: "Happy birthday Sofia!",
      text: "15 years ago I became a great-aunt and the world got a little brighter. Feliz quinceañera princesa! The flan recipe lives on. 🎂",
      occurredAt: "2021-06-12T19:00:00.000Z",
      personIds: [],
      metadata: { reactions: 112 },
    },
    {
      type: "post",
      source: "meta_instagram",
      title: "Sofia's quinceañera",
      text: "My beautiful great-niece in her dress. Fifteen years of joy. #quinceañera #family #blessed",
      occurredAt: "2021-06-12T21:30:00.000Z",
      personIds: [],
      mediaRefs: [demoImage("instagram-quinceanera.svg")],
      metadata: { likes: 203 },
    },
    {
      type: "note",
      source: "manual",
      title: "Voice note transcript",
      text: "Recorded at the kitchen table, March 2022: 'Tell them about the time your father and I drove to Niagara Falls with no map. We got lost three times and it was the best trip we ever took. Getting lost together is underrated.'",
      occurredAt: "2022-03-08T15:00:00.000Z",
      personIds: [],
      metadata: { recordedBy: "Maria" },
    },
    {
      type: "photo",
      source: "manual",
      title: "Wedding day, 1978",
      text: "Scanned from the album in the hall closet. Rose and Antonio outside St. Mary's. She said yes before he finished the question.",
      occurredAt: "1978-09-16T16:00:00.000Z",
      personIds: [],
      mediaRefs: [demoImage("instagram-wedding.svg")],
      metadata: { scannedBy: "James", originalFormat: "polaroid" },
    },
    {
      type: "message",
      source: "sms",
      title: "Text from Rose",
      text: "Don't forget your coat. It's colder than the forecast says. Love you.",
      occurredAt: "2019-12-01T07:12:00.000Z",
      personIds: [],
      metadata: { sender: "Rose Martinez", address: "+15551234567" },
    },
    {
      type: "message",
      source: "sms",
      title: "Text from James",
      text: "Can you pick up my prescription when you're out? CVS on Main St.",
      occurredAt: "2020-03-15T11:08:00.000Z",
      personIds: [],
      metadata: { sender: "James", address: "+15551234567" },
    },
    {
      type: "message",
      source: "sms",
      title: "Text from Rose",
      text: "Already done. It's in the blue bag by the door. Take the lasagna out of the freezer too.",
      occurredAt: "2020-03-15T11:19:00.000Z",
      personIds: [],
      metadata: { sender: "Rose Martinez", address: "+15551234567" },
    },
    {
      type: "message",
      source: "imessage",
      title: "iMessage from Sofia",
      text: "ABUELA ROSE!!! I got the dress!!! It's perfect 😭💕",
      occurredAt: "2021-05-28T16:02:00.000Z",
      personIds: [],
      metadata: { sender: "Sofia", service: "iMessage" },
    },
    {
      type: "message",
      source: "imessage",
      title: "iMessage from Rose",
      text: "Send me a picture RIGHT NOW princesa. I'm crying at the kitchen table.",
      occurredAt: "2021-05-28T16:05:00.000Z",
      personIds: [],
      metadata: { sender: "Rose Martinez", service: "iMessage" },
    },
    {
      type: "post",
      source: "meta_instagram",
      title: "Christmas cookies",
      text: "Annual cookie marathon with the grandkids. Flour everywhere. Wouldn't have it any other way. 🍪",
      occurredAt: "2019-12-22T11:30:00.000Z",
      personIds: [],
      mediaRefs: [demoImage("instagram-cookies.svg")],
      metadata: { likes: 134 },
    },
    {
      type: "post",
      source: "meta_instagram",
      title: "Sunday market flowers",
      text: "Stopped at the farmers market on the way home. These go in Maria's bouquet tomorrow. #flowers #local #sunday",
      occurredAt: "2020-04-19T10:15:00.000Z",
      personIds: [],
      mediaRefs: [demoImage("instagram-market.svg")],
      metadata: { likes: 76, lat: 41.8897, lng: -87.6334, place: "Green City Market" },
    },
    {
      type: "email",
      source: "email",
      title: "Recipe card scan",
      text: "Maria — here is the flan recipe, written exactly as my mother gave it to me in 1962. The secret is the water bath and patience. Never rush a flan.\n\nCon cariño,\nRose",
      occurredAt: "2020-02-20T10:00:00.000Z",
      personIds: [],
      metadata: { from: "rose.martinez@gmail.com", to: "maria.m@gmail.com" },
    },
    {
      type: "post",
      source: "meta_facebook",
      title: "Neighborhood block party",
      text: "Thank you to everyone who came out today. Rose's famous empanadas disappeared in twenty minutes — I'll take that as a compliment. Already planning next year.",
      occurredAt: "2016-08-17T20:00:00.000Z",
      personIds: [],
      mediaRefs: [demoImage("instagram-block-party.svg")],
      metadata: { reactions: 63, lat: 41.8819, lng: -87.6231, place: "Oak Street block party" },
    },
    // ——— Expanded demo archive ———
    {
      type: "post",
      source: "meta_instagram",
      title: "Sunday kitchen",
      text: "The pot is never small enough. Arroz con pollo for twelve — again. #sundaydinner #familia #chicago",
      occurredAt: "2018-03-11T19:00:00.000Z",
      personIds: [],
      mediaRefs: [demoImage("instagram-kitchen.svg")],
      metadata: { likes: 156, tags: ["cooking", "family", "sunday"] },
    },
    {
      type: "photo",
      source: "google_photos",
      title: "Family reunion picnic",
      text: "Martinez clan at Lincoln Park. Someone always brings the potato salad recipe nobody can replicate.",
      occurredAt: "2015-07-04T14:30:00.000Z",
      personIds: [],
      mediaRefs: [demoImage("instagram-reunion.svg")],
      metadata: { album: "Martinez Reunion 2015", faces: 14 },
    },
    {
      type: "post",
      source: "meta_instagram",
      title: "80 candles",
      text: "They said I couldn't blow them all out. Watch me. 🎂 #80andflourishing",
      occurredAt: "2022-03-12T20:00:00.000Z",
      personIds: [],
      mediaRefs: [demoImage("instagram-birthday.svg")],
      metadata: { likes: 312, comments: 48 },
    },
    {
      type: "note",
      source: "manual",
      title: "Niagara Falls story",
      text: "Antonio and I drove to Niagara with no map, three wrong turns, and the best sandwiches from a gas station in Buffalo. We got lost on purpose after that. Getting lost together is underrated.",
      occurredAt: "1983-08-14T12:00:00.000Z",
      personIds: [],
      mediaRefs: [demoImage("instagram-niagara.svg")],
      metadata: { recordedBy: "Rose Martinez" },
    },
    {
      type: "post",
      source: "meta_instagram",
      title: "First snow with the littles",
      text: "Three coats each and they still wanted to stay outside. Hot chocolate emergency inside. ☃️",
      occurredAt: "2018-12-09T15:45:00.000Z",
      personIds: [],
      mediaRefs: [demoImage("instagram-grandkids.svg")],
      metadata: { likes: 198, place: "Oak Street, Chicago" },
    },
    {
      type: "post",
      source: "meta_instagram",
      title: "Porch season",
      text: "Rocking chair weather. Tulips from Maria's cutting. Coffee number two. #spring #porch #chicago",
      occurredAt: "2020-04-26T09:30:00.000Z",
      personIds: [],
      mediaRefs: [demoImage("instagram-porch.svg")],
      metadata: { likes: 92, lat: 41.8781, lng: -87.6298 },
    },
    {
      type: "photo",
      source: "manual",
      title: "Antonio, workshop days",
      text: "Dad in the garage after his shift. He built every shelf in our first house with hands that never stopped moving.",
      occurredAt: "1985-06-20T17:00:00.000Z",
      personIds: [],
      mediaRefs: [demoImage("photo-antoni.svg")],
      metadata: { scannedBy: "James", originalFormat: "35mm" },
    },
    {
      type: "photo",
      source: "google_photos",
      title: "James — graduation",
      text: "First in the family with a university degree. Rose cried through the whole ceremony and didn't care who saw.",
      occurredAt: "2019-05-18T11:00:00.000Z",
      personIds: [],
      mediaRefs: [demoImage("photo-graduation.svg")],
      metadata: { album: "James Graduation 2019" },
    },
    {
      type: "message",
      source: "whatsapp",
      title: "WhatsApp from Maria",
      text: "Tía are you okay? The news says stay home. Do you need groceries?",
      occurredAt: "2020-03-18T14:22:00.000Z",
      personIds: [],
      metadata: { sender: "Maria", chat: "Family Group" },
    },
    {
      type: "message",
      source: "whatsapp",
      title: "WhatsApp from Rose",
      text: "I'm fine mija. Made enough soup for the block. Left containers on the porch — tell James to pick his up.",
      occurredAt: "2020-03-18T14:35:00.000Z",
      personIds: [],
      metadata: { sender: "Rose Martinez", chat: "Family Group" },
    },
    {
      type: "message",
      source: "whatsapp",
      title: "WhatsApp from James",
      text: "On my way. Mom please don't go door to door, use the group chat.",
      occurredAt: "2020-03-18T14:41:00.000Z",
      personIds: [],
      metadata: { sender: "James", chat: "Family Group" },
    },
    {
      type: "message",
      source: "whatsapp",
      title: "WhatsApp from Rose",
      text: "Don't tell me how to love my neighbors. 😂 Soup is on the blue table.",
      occurredAt: "2020-03-18T14:48:00.000Z",
      personIds: [],
      metadata: { sender: "Rose Martinez", chat: "Family Group" },
    },
    {
      type: "message",
      source: "imessage",
      title: "iMessage from James",
      text: "Happy anniversary Mom and Dad. Wish I could take you both to dinner.",
      occurredAt: "2018-09-16T08:00:00.000Z",
      personIds: [],
      metadata: { sender: "James", service: "iMessage" },
    },
    {
      type: "message",
      source: "imessage",
      title: "iMessage from Rose",
      text: "Your father would've loved that. I'm making his favorite tonight — arroz con pollo, always. He'd say the secret is the sofrito.",
      occurredAt: "2018-09-16T08:12:00.000Z",
      personIds: [],
      metadata: { sender: "Rose Martinez", service: "iMessage" },
    },
    {
      type: "email",
      source: "email",
      title: "Garden club minutes",
      text: "Dear Rose,\n\nCongratulations on winning Best Rose Display for the third consecutive year. The judges specifically noted your heirloom varieties.\n\nSee you at the October meeting.\n\nMargaret Chen, Secretary\nHyde Park Garden Club",
      occurredAt: "2019-05-20T10:30:00.000Z",
      personIds: [],
      metadata: { from: "secretary@hydeparkgarden.org", to: "rose.martinez@gmail.com" },
    },
    {
      type: "message",
      source: "google_messages",
      title: "Text from Sofia",
      text: "Abuela!! I got an A on the history paper about YOUR garden club!! Can I interview you Thursday?",
      occurredAt: "2021-04-08T16:20:00.000Z",
      personIds: [],
      metadata: { sender: "Sofia", service: "Google Messages" },
    },
    {
      type: "message",
      source: "google_messages",
      title: "Text from Rose",
      text: "Thursday is perfect. I'll make tea and pull out every ribbon since 1998. Bring your notebook.",
      occurredAt: "2021-04-08T16:28:00.000Z",
      personIds: [],
      metadata: { sender: "Rose Martinez", service: "Google Messages" },
    },
    {
      type: "message",
      source: "meta_messenger",
      title: "Message from Elena",
      text: "Rose — the empanada recipe from the block party? My husband hasn't stopped talking about them.",
      occurredAt: "2016-08-18T09:15:00.000Z",
      personIds: [],
      metadata: { sender: "Elena Ruiz" },
    },
    {
      type: "message",
      source: "meta_messenger",
      title: "Message from Rose",
      text: "I'll drop a handwritten copy on your porch tomorrow. The trick is cold butter and patience.",
      occurredAt: "2016-08-18T09:42:00.000Z",
      personIds: [],
      metadata: { sender: "Rose Martinez" },
    },
    {
      type: "message",
      source: "sms",
      title: "Text from James",
      text: "Mom your Facebook post about the block party has 200 shares. You're famous.",
      occurredAt: "2016-08-18T22:10:00.000Z",
      personIds: [],
      metadata: { sender: "James", address: "+15551234567" },
    },
    {
      type: "message",
      source: "sms",
      title: "Text from Rose",
      text: "Famous for empanadas is the only fame I want. Tell Sofia I saved her a box.",
      occurredAt: "2016-08-18T22:18:00.000Z",
      personIds: [],
      metadata: { sender: "Rose Martinez", address: "+15551234567" },
    },
    {
      type: "post",
      source: "meta_facebook",
      title: "Thanksgiving gratitude",
      text: "Twenty-two people at one table. Three pies, two turkeys, and one grandmother who refused to sit down until everyone had seconds. Grateful doesn't cover it.",
      occurredAt: "2019-11-28T21:00:00.000Z",
      personIds: [],
      metadata: { reactions: 89, comments: 24 },
    },
    {
      type: "message",
      source: "imessage",
      title: "iMessage from Maria",
      text: "Tía I'm bringing the sweet potato casserole. Do you still have the big serving spoon?",
      occurredAt: "2019-11-27T10:00:00.000Z",
      personIds: [],
      metadata: { sender: "Maria", service: "iMessage" },
    },
    {
      type: "message",
      source: "imessage",
      title: "iMessage from Rose",
      text: "The spoon is washed and waiting. Start the oven at 350 when you get here. Love you.",
      occurredAt: "2019-11-27T10:08:00.000Z",
      personIds: [],
      metadata: { sender: "Rose Martinez", service: "iMessage" },
    },
    {
      type: "email",
      source: "email",
      title: "Fwd: James's acceptance letter",
      text: "Antonio — he got in. Full ride partial. Our boy. I read the letter four times and cried each time.\n\n— Rose",
      occurredAt: "2015-03-22T19:45:00.000Z",
      personIds: [],
      metadata: { from: "rose.martinez@gmail.com", to: "antonio.martinez@workmail.com" },
    },
    {
      type: "message",
      source: "whatsapp",
      title: "WhatsApp from James",
      text: "Mom I'm thinking of law school. Too late to ask your opinion?",
      occurredAt: "2019-06-02T20:15:00.000Z",
      personIds: [],
      metadata: { sender: "James", chat: "Rose & James" },
    },
    {
      type: "message",
      source: "whatsapp",
      title: "WhatsApp from Rose",
      text: "It's never too late to ask. Your father wanted you to choose work that helps people. Follow that.",
      occurredAt: "2019-06-02T20:22:00.000Z",
      personIds: [],
      metadata: { sender: "Rose Martinez", chat: "Rose & James" },
    },
    {
      type: "story",
      source: "meta_instagram",
      title: "Behind the scenes — cookie chaos",
      text: "Flour on the ceiling. No regrets. 🍪",
      occurredAt: "2019-12-22T14:00:00.000Z",
      personIds: [],
      mediaRefs: [demoImage("instagram-cookies.svg")],
      metadata: { views: 412, expiresHours: 24 },
    },
    {
      type: "post",
      source: "meta_facebook",
      title: "Antonio's rose bush",
      text: "Planted a new climbing rose where Antonio's workshop used to be. He always said roses were stubborn — like him. It's already blooming.",
      occurredAt: "2017-05-20T11:00:00.000Z",
      personIds: [],
      mediaRefs: [demoImage("instagram-garden.svg")],
      metadata: { reactions: 78, comments: 19 },
    },
    {
      type: "note",
      source: "manual",
      title: "Recipe card — empanadas",
      text: "Dough: 3 cups flour, 1 tsp salt, 1 cup cold butter diced, ice water until it holds. Filling: ground beef, olives, raisins, cumin, one hard egg per dozen. Fold, crimp, egg wash. 375°F until golden. Never rush.",
      occurredAt: "2016-08-19T08:00:00.000Z",
      personIds: [],
      metadata: { recordedBy: "Rose Martinez", category: "recipe" },
    },
    {
      type: "note",
      source: "manual",
      title: "Recipe card — sofrito base",
      text: "Green bell pepper, cubanelle, garlic, cilantro, ají dulce if you can find it. Blend coarse. Freeze in ice cube trays. Every Sunday pot starts with two cubes.",
      occurredAt: "2018-03-10T09:00:00.000Z",
      personIds: [],
      metadata: { recordedBy: "Rose Martinez", category: "recipe" },
    },
    {
      type: "call_log",
      source: "sms",
      title: "Call with James",
      text: "Outgoing call — 47 minutes",
      occurredAt: "2020-04-05T19:30:00.000Z",
      personIds: [],
      metadata: { contact: "James", durationSec: 2820, direction: "outgoing" },
    },
    {
      type: "call_log",
      source: "sms",
      title: "Call with Maria",
      text: "Incoming call — 22 minutes",
      occurredAt: "2021-06-13T10:15:00.000Z",
      personIds: [],
      metadata: { contact: "Maria", durationSec: 1320, direction: "incoming" },
    },
    {
      type: "message",
      source: "imessage",
      title: "iMessage from Sofia",
      text: "Abuela can you teach me to crimp empanadas like you? Mine look sad.",
      occurredAt: "2022-01-08T14:00:00.000Z",
      personIds: [],
      metadata: { sender: "Sofia", service: "iMessage" },
    },
    {
      type: "message",
      source: "imessage",
      title: "iMessage from Rose",
      text: "Sad empanadas still taste good. Come Saturday — we'll make six dozen and you can practice on the ugly ones first.",
      occurredAt: "2022-01-08T14:06:00.000Z",
      personIds: [],
      metadata: { sender: "Rose Martinez", service: "iMessage" },
    },
    {
      type: "message",
      source: "google_messages",
      title: "Text from James",
      text: "Market flowers look great in your post. Did you get the peonies?",
      occurredAt: "2020-04-19T11:00:00.000Z",
      personIds: [],
      metadata: { sender: "James", service: "Google Messages" },
    },
    {
      type: "message",
      source: "google_messages",
      title: "Text from Rose",
      text: "Got the last bunch. Maria's bouquet is going to make her cry — the good kind.",
      occurredAt: "2020-04-19T11:04:00.000Z",
      personIds: [],
      metadata: { sender: "Rose Martinez", service: "Google Messages" },
    },
    {
      type: "email",
      source: "email",
      title: "Re: Sofia's interview project",
      text: "Sofia — attached are the garden club photos you asked for. Tell your teacher the pink rose is a 1962 cutting from my mother's garden in San Juan.\n\nLove,\nAbuela Rose",
      occurredAt: "2021-04-10T18:00:00.000Z",
      personIds: [],
      metadata: { from: "rose.martinez@gmail.com", to: "sofia.m@gmail.com" },
    },
    {
      type: "post",
      source: "meta_facebook",
      title: "Easter at St. Mary's",
      text: "Same pew we've sat in since 1978. Sofia in the choir this year — her voice carries like her great-grandmother's.",
      occurredAt: "2018-04-01T12:30:00.000Z",
      personIds: [],
      metadata: { reactions: 54, place: "St. Mary's, Chicago" },
    },
    {
      type: "message",
      source: "meta_messenger",
      title: "Message from James",
      text: "Mom did you take your blood pressure this morning?",
      occurredAt: "2021-10-14T08:30:00.000Z",
      personIds: [],
      metadata: { sender: "James" },
    },
    {
      type: "message",
      source: "meta_messenger",
      title: "Message from Rose",
      text: "Yes doctor. 118/76. Now stop worrying and eat your breakfast.",
      occurredAt: "2021-10-14T08:38:00.000Z",
      personIds: [],
      metadata: { sender: "Rose Martinez" },
    },
    {
      type: "message",
      source: "whatsapp",
      title: "WhatsApp from Maria",
      text: "Tía the hospice nurse said your garden visit yesterday meant everything to her.",
      occurredAt: "2022-10-22T16:00:00.000Z",
      personIds: [],
      metadata: { sender: "Maria", chat: "Family Group" },
    },
    {
      type: "message",
      source: "whatsapp",
      title: "WhatsApp from Rose",
      text: "She helped me when Antonio was sick. A cutting of his rose is the least I could do.",
      occurredAt: "2022-10-22T16:12:00.000Z",
      personIds: [],
      metadata: { sender: "Rose Martinez", chat: "Family Group" },
    },
    {
      type: "photo",
      source: "google_photos",
      title: "Cookie marathon — aftermath",
      text: "Flour on every surface. Three grandkids asleep on the couch. Best chaos.",
      occurredAt: "2019-12-22T16:00:00.000Z",
      personIds: [],
      mediaRefs: [demoImage("instagram-cookies.svg")],
      metadata: { album: "Christmas 2019" },
    },
    {
      type: "photo",
      source: "google_photos",
      title: "Quinceañera — family table",
      text: "The flan recipe made it to the dessert table. Maria cried. Sofia danced until midnight.",
      occurredAt: "2021-06-12T23:00:00.000Z",
      personIds: [],
      mediaRefs: [demoImage("instagram-quinceanera.svg")],
      metadata: { album: "Sofia Quinceañera 2021" },
    },
    {
      type: "message",
      source: "sms",
      title: "Text from Rose",
      text: "Sofia — the dress photo made my whole week. You look like your mother at fifteen.",
      occurredAt: "2021-05-28T16:20:00.000Z",
      personIds: [],
      metadata: { sender: "Rose Martinez", address: "+15559876543" },
    },
    {
      type: "message",
      source: "sms",
      title: "Text from Sofia",
      text: "I love you abuela 😭💕 saving a dance for you at the party",
      occurredAt: "2021-05-28T16:25:00.000Z",
      personIds: [],
      metadata: { sender: "Sofia", address: "+15559876543" },
    },
    {
      type: "post",
      source: "meta_facebook",
      title: "Farmers market regular",
      text: "Every Sunday rain or shine. The flower vendor saves peonies for me now. Small kindnesses add up.",
      occurredAt: "2020-05-03T10:00:00.000Z",
      personIds: [],
      mediaRefs: [demoImage("instagram-market.svg")],
      metadata: { reactions: 41, place: "Green City Market" },
    },
    {
      type: "message",
      source: "imessage",
      title: "iMessage from James",
      text: "Landing at Midway in an hour. Need anything from the store?",
      occurredAt: "2022-03-11T14:00:00.000Z",
      personIds: [],
      metadata: { sender: "James", service: "iMessage" },
    },
    {
      type: "message",
      source: "imessage",
      title: "iMessage from Rose",
      text: "Just you. And maybe milk. The good kind.",
      occurredAt: "2022-03-11T14:05:00.000Z",
      personIds: [],
      metadata: { sender: "Rose Martinez", service: "iMessage" },
    },
    {
      type: "email",
      source: "email",
      title: "Voice note backup",
      text: "Maria — I recorded three hours of stories at the kitchen table. Files are in the shared folder. Label says 'for when I'm not fast enough on the phone.'\n\nRose",
      occurredAt: "2022-02-28T20:00:00.000Z",
      personIds: [],
      metadata: { from: "rose.martinez@gmail.com", to: "maria.m@gmail.com" },
    },
  ];

  return samples.map((sample) => {
    const text = sample.text;
    const occurredAt = sample.occurredAt;
    return {
      ...sample,
      id: generateId(),
      memorialId,
      importedAt,
      mediaRefs: (sample.mediaRefs ?? []).map((ref) => ({ ...ref, id: generateId() })),
      contentHash: contentHash([sample.source, sample.type, occurredAt, sample.title ?? "", text]),
    };
  });
}

export function demoSubjectName(): string {
  return "Rose Martinez";
}
